version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
    volumes:
      - "./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
    restart: unless-stopped
    ports:
      - "5601:5601"
    container_name: kibana
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    container_name: elasticsearch
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./data/esdata:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:${KIBANA_VERSION}
    volumes:
      - "./config/logstash/logstash.conf:/config-dir/logstash.conf"
    restart: unless-stopped
    command: logstash -f /config-dir/logstash.conf
    ports:
      - "9600:9600"
      - "7777:7777"
    container_name: logstash
    depends_on:
      - elasticsearch
      - kafka101
      - kafka102
      - kafka103

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    ports:
      - "3000:3000"
    environment:
      GF_PATHS_DATA: /var/lib/grafana
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    ports:
      - "9090:9090"
    user: root
    volumes:
      - ./config/prometheus:/etc/prometheus
      - ./data/prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    restart: unless-stopped
    container_name: prometheus

  kafka-lag-exporter:
    image: lightbend/kafka-lag-exporter:0.5.5
    container_name: kafka-lag-exporter
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - ./config/kafka-lag-exporter/:/opt/docker/conf/

  jmx-kafka101:
    image: sscaling/jmx-prometheus-exporter
    ports:
      - "5556:5556"
    environment:
      CONFIG_YML: "/etc/jmx_exporter/config.yml"
      JVM_OPTS: ${JVM_OPTS}
    volumes:
      - ./config/jmx_exporter/config_exporter1.yml:/etc/jmx_exporter/config.yml
    container_name: jmx-kafka101
    restart: unless-stopped
    depends_on:
      - kafka101

  jmx-kafka102:
    image: sscaling/jmx-prometheus-exporter
    ports:
      - "5557:5556"
    environment:
      CONFIG_YML: "/etc/jmx_exporter/config.yml"
      JVM_OPTS: ${JVM_OPTS}
    volumes:
      - ./config/jmx_exporter/config_exporter2.yml:/etc/jmx_exporter/config.yml
    container_name: jmx-kafka102
    restart: unless-stopped
    depends_on:
      - kafka102

  jmx-kafka103:
    image: sscaling/jmx-prometheus-exporter
    ports:
      - "5558:5556"
    environment:
      CONFIG_YML: "/etc/jmx_exporter/config.yml"
      JVM_OPTS: ${JVM_OPTS}
    volumes:
      - ./config/jmx_exporter/config_exporter3.yml:/etc/jmx_exporter/config.yml
    container_name: jmx-kafka103
    restart: unless-stopped
    depends_on:
      - kafka103

  zk1:
    image: confluentinc/cp-zookeeper:${CONFLUENT_VERSION}
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    restart: unless-stopped
    container_name: zookeeper1

  kafka101:
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION}
    depends_on:
      - zk1
    ports:
      - "9091:9091"
      - "9991:9991"
    container_name: kafka101
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_JMX_PORT: 9991
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_HOST}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka101:29092,PLAINTEXT_HOST://localhost:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka101:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: ${ZOOKEEPER_HOST}
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'

  kafka102:
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION}
    depends_on:
      - zk1
    ports:
      - "9092:9092"
      - "9992:9992"
    container_name: kafka102
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_JMX_PORT: 9992
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_HOST}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka102:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka102:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: ${ZOOKEEPER_HOST}
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'

  kafka103:
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION}
    depends_on:
      - zk1
    ports:
      - "9093:9093"
      - "9993:9993"
    container_name: kafka103
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 103
      KAFKA_JMX_PORT: 9993
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_HOST}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka103:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka103:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: ${ZOOKEEPER_HOST}
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'

  mysql:
    image: mysql:8.0
    ports:
     - "3307:3306"
    restart: unless-stopped
    environment:
     - MYSQL_ROOT_PASSWORD=${PW}
     - LANG=C.UTF-8
    container_name: database
    volumes:
      - ./data/db:/var/lib/mysql
      - ./config/db/logistic.sql:/docker-entrypoint-initdb.d/logistic.sql

  connect:
    image: debezium/connect:2.0
    ports:
     - "8083:8083"
    environment:
     - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS}
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=${CONFIG_STORAGE_TOPIC}
     - OFFSET_STORAGE_TOPIC=${OFFSET_STORAGE_TOPIC}
     - STATUS_STORAGE_TOPIC=${STATUS_STORAGE_TOPIC}
    container_name: debezium
    depends_on:
      - kafka101
      - kafka102
      - kafka103
      - mysql
    restart: unless-stopped

  manager:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${BOOTSTRAP_SERVERS}
    container_name: ui_kafka
    restart: unless-stopped
    depends_on:
      - zk1

  app:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/app
    restart: always
    container_name: app
    depends_on:
      - connect
      - kafka101
      - kafka102
      - kafka103

  server:
    build: ./server
    ports:
      - "8088:8088"
    volumes:
      - ./server:/server
      - /server/node_modules
    restart: always
    container_name: server

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    container_name: proxy
    depends_on:
      - server

  redis:
    image: redis:6.2-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./data/cache:/data
    restart: always
    container_name: redis
